from typing import Protocol


class UserRepository(Protocol):
    async def create(self, *, name: str, email: str, password_hash: str) -> dict: ...
    async def get_by_email(self, email: str) -> dict | None: ...
    async def get_by_id(self, user_id: str) -> dict | None: ...
    async def set_workspace_id(self, *, user_id: str, workspace_id: str) -> None: ...
    async def update_password(self, *, user_id: str, password_hash: str) -> None: ...
